<a href="https://colab.research.google.com/github/PRyuC/Pascal_INFO5502_Summer2022/blob/main/lab_assignment_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The third Lab-assignment (07/22/2022 11:59'AM' - 07/26/2022 11:59PM, 50 points in total)

The purpose of this exercise is to understand users' information needs, then collect data from different sources for analysis.

Question 1 (10 points). Fomulate your domain problem: Describe an interesting research question (or practical question) you have in mind, what kind of data should be collected to answer the question(s)? How many data needed for the analysis? The detail steps for collecting and save the data.

In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here: 

Research question: How do consumers from the U.S. and the U.K. differ in expressing their opinions on Amazon Product Reviews?
For instance, British people are well know for their dry humor that includes sarcasm. Therefore, it would be interesting to 
compare if users from the U.K. are proportionally more likely to use sarcasm in their negative Amazon reviews 
compared to their american counterparts. Other English-speaking coutries could be considered but starting with these two 
seems like the logical choice. More than just sarcasm could be explored. For instance, what expressions regarding sentiment
are more common to each specific region, if one is more likely to use sweard words and which ones are used depending on the region, etc.

Kind of data to collect: The data would be amazon reviews from both amazon.com for the U.S. users and 
from amazon.co.uk for the British users. As a first step, I have decided to explore movie reviews as these seem to have 
a higher variation of opinions than normal products and are hypothetically more likely to induce sarcasm. The username,
review, numbers of stars, title, and date of the review could be scraped among other information. 

How much data needed: Half of the reviews would be from american users and half from U.K. users. A lot of data would be needed
to make sure to have enough for a training, a validation and a test set to label the reviews as sarcastic or not later on if that is the main
purpose of the research. A first pass on one movie could be a good start, however collecting reviews for as many movies as possible would be even better.

Steps to collect and save the data: I will use webscraping with Python using requests and BeautifulSoup to collect the data and save it as
a csv file. Multiple information for different items would be scraped: the review itself; the date (which helpfully includes the region on Amazon);
the title of the review, the username, and the rating.



'''

Question 2 (30 points). Collect your data to answer the research problem: Write python code to collect 1000 data samples you discussed above.

In [12]:
# You code here (Please add comments in the code):

# importing necessary modules
import pandas as pd              # pandas for dataframe
import requests                  # requests to send http requests to amazon
from bs4 import BeautifulSoup    # BeautifulSoup to parse the html
from datetime import datetime    # datetime to save the csv file as a date

# headers to bypass and be able to scrape amazon
# found by inspecting page, going to Network, copying first file as cURL (bash), transforming to python format 
headers = {
    'authority': 'www.amazon.com',
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'accept-language': 'en-GB,en;q=0.9,en-US;q=0.8,fr;q=0.7,es-419;q=0.6,es;q=0.5',
    'cache-control': 'max-age=0',
    # Requests sorts cookies= alphabetically
    # 'cookie': 'session-id=145-3052181-6604163; i18n-prefs=USD; skin=noskin; ubid-main=134-5698716-5974708; lc-main=en_US; session-id-time=2082787201l; av-timezone=America/Chicago; session-token=/y+u5JOruQhjiyUlmvMudY5K2tXmf/Mo1k9tpdk9PksSwxgzq5bugoj/hGKCDpOIIP0ILoZ47BWG43FAPi4WFjULlHISWR0GrucaLEWuwmr78sDMms6lR/XSobawnJnEN5QHe9ml2B9+HC4kvRfodHXMOOpX2oqrOVueaIPNYfoL41boHwbkk0mDqW0jFG2U3sE42MJDqIgOX083YC006w==; csm-hit=tb:NZTZ3SQK18MQGJ30526E+sa-6JGP1NRME3SY63NZJ8WX-GP9RMEK7667BZ5DKEZA6|1658844585175&t:1658844585175&adb:adblk_yes',
    'device-memory': '8',
    'downlink': '10',
    'dpr': '1.25',
    'ect': '4g',
    'referer': 'https://www.amazon.com/Live-Die-Repeat-Edge-Tomorrow/dp/B00KW27K4K/ref=sr_1_1_sspa?crid=3P1IXE0AIU7DN&keywords=movies&qid=1658844509&sprefix=movie%2Caps%2C171&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyWERZMERIODFENFomZW5jcnlwdGVkSWQ9QTEwNDI1MDRUSUQzQzMwQkZOTU8mZW5jcnlwdGVkQWRJZD1BMDU5ODE2MjJCOFcyUE1JVU9TRU4md2lkZ2V0TmFtZT1zcF9hdGYmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl',
    'rtt': '100',
    'sec-ch-device-memory': '8',
    'sec-ch-dpr': '1.25',
    'sec-ch-ua': '".Not/A)Brand";v="99", "Google Chrome";v="103", "Chromium";v="103"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-ch-viewport-width': '1229',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'same-origin',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36',
    'viewport-width': '1229',
}


# getting the first page of urls for amazon.com and amazon.co.uk
urls_us = ["https://www.amazon.com/product-reviews/B00KW27K4K/ref=cm_cr_arp_d_viewopt_srt?ie=UTF8&reviewerType=all_reviews&sortBy=recent&pageNumber=1"]
urls_uk = ["https://www.amazon.co.uk/product-reviews/B00O0NZ6IY/ref=cm_cr_arp_d_viewopt_srt?ie=UTF8&reviewerType=all_reviews&sortBy=recent&pageNumber=1"]


# getting the next pages by adding each number from 2 to 100 at the end of the url
for n in range(2, 101):
  link_us = "https://www.amazon.com/product-reviews/B00KW27K4K/ref=cm_cr_arp_d_viewopt_srt?ie=UTF8&reviewerType=all_reviews&sortBy=recent&pageNumber="
  next_page_us = link_us + str(n) # adding each number to the string
  urls_us.append(next_page_us)    # appending each url to the list

  link_uk = "https://www.amazon.co.uk/product-reviews/B00O0NZ6IY/ref=cm_cr_arp_d_viewopt_srt?ie=UTF8&reviewerType=all_reviews&sortBy=recent&pageNumber="
  next_page_uk = link_uk + str(n)
  urls_uk.append(next_page_uk)


# defining a function with 1 parameter for a soup object
def get_usernames(soup_object):          
  try:
    usernames = soup_object.find("div", {"class": "a-profile-content"}).get_text() # finding specific html for usernames, only getting the text
    return usernames.strip() # removing leading and trailing spaces
  except Exception as e:
    print(e)

# defining other functions the same way for all other information wanted starting with the numbers of stars
def get_stars(soup_object):
  try:
    stars = soup_object.find("span", {"class": "a-icon-alt"}).get_text()
    return stars.strip()
  except Exception as e:
    print(e)


# getting the title, but sometimes returns 'NoneType' object has no attribute 'get_text', need to fix
def get_title(soup_object):
  try:
    title = soup_object.find("a", {"class": "a-size-base a-link-normal review-title a-color-base review-title-content a-text-bold"}).get_text()
    return title.strip()
  except Exception as e:
    pass                          # passing error for now
    #print(e)


# getting the date
def get_date(soup_object):
  try:
    date = soup_object.find("span", {"class": "review-date"}).get_text()
    return date.strip()
  except Exception as e:
    print(e)


# getting the main text of the review
def get_body(soup_object):
  try:
    body = soup_object.find("span", {"class": "a-size-base review-text review-text-content"}).get_text()
    return body.strip()
  except Exception as e:
    print(e)


# function to put all of this together in a dictionary to return names of the columns as index and data of each review as values
def get_all_components(a_review):             
  return {
      "Username": get_usernames(a_review),
      "Stars": get_stars(a_review),
      "Title": get_title(a_review),
      "Date": get_date(a_review),
      "Review": get_body(a_review)
  }



# function to request the html of any page
def get_page_html(page_url):
    resp = requests.get(page_url, headers=headers)   #requesting the html
    return resp.text                                 #returning the text

# function to find reviews from any page
def get_reviews_from_html(page_html):
    soup = BeautifulSoup(page_html, "lxml")         #parsing the html with BeautifulSoup, using the lxml parser
    reviews = soup.find_all("div", {"class": "a-section celwidget"})  #finding the section where each indidivual review is, finding all
    return reviews                                                    #returning them



# appending all data to a list
all_results = []                            # creating a new list
for u in urls_us:                           
  html = get_page_html(u)                   # checking all urls as html
  reviews = get_reviews_from_html(html)     # getting all reviews for each url
  for rev in reviews:
    data = get_all_components(rev)          # getting the data for all 5 fields considered for each review
    all_results.append(data)                # appending data to the list


# doing the same for the UK urls
for u in urls_uk:
  html = get_page_html(u)
  reviews = get_reviews_from_html(html)
  for rev in reviews:
    data = get_all_components(rev)
    all_results.append(data)


out = pd.DataFrame.from_records(all_results) # transforming output to a dataframe, using from_records since it is a list of dictionaries
save_name = f"{datetime.now().strftime('%Y-%m-%d-%H:%M')}.csv" #naming file as the date (GMT)
out.to_csv(save_name) #transforming and saving dataframe to csv file

Question 3 (10 points). Understand the data quality: Search a second hand dataset (any dataset) from kaggle or other websites. Describe the data quality problem of the dataset and explain your strtegy to clean the data.

In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):
'''

Please write you answer here:

For this question, I have looked for an unclean dataset from kaggle and coincidently found one 
made for this purpose and related to movies named "MOVIES DATASET FOR FEATURE EXTRACION ,PREDICTION"

Quality problem of the dataset: a lot of the values are empty, unclear and not formatted properly.

Strategy to clean the data: format the values appropriately for those for which it is 
possible with text preprocessing and, if some items have no values at all, possibly drop them 
(depending on the objective of the research).

To answer both of these questions in more detail, each field would need to be considered separately. 
For instance, the first field, called MOVIES, is the name of the movie. One of the issues is that there
seems to be duplicates which should be deleted. Also, the name is MOVIES however there are a lot of 
TV shows as well. 

The second field, called YEAR, is the year the movie/show was released. A regular expression would be helpful 
to delete extraneous symbols such as parentheses and only keep years (one year for the movies, possibly two 
for the TV shows since they have a start and an end year).

The third field, called GENRE, is the genre of the movie or TV show and seems fine as is. 
Some items have multiple categories which should be kept in mind if comparing different genres.

The fourth field, called RATING, which is the rating out of 10, has the issue of not having a 
rating for some items. These could be excluded depending on the goal of the study.

The fifth field, called ONE-LINE, is a description of the movie/show and seems fine besides
the fact that some do not have any description and could be omitted. Moreover, the name is 
not very descriptive and could be modified.

The sixth field, called STARS, is the list of stars except some include the director as well. The name STARS
is also confusing since it sometimes refer to the ratings on other websites such as Amazon. Since the name of
the field is stars, I would infer that only those names are wanted. Therefore, I would deleted everything before 
the names of the stars as well as modifying STARS to STARRING.

The seventh field, called VOTES, is the number of votes (related to the rating) where the only issue is that 
some items do not have this value. Only items with a number of votes over a certain treshold could be a good idea, 
especially if the rating is important.

The eight field, called RunTime, is the length of the movie/show. A few of the items do not have this value which
could be deleted if the goal was to compare the length (for instance between different genres).

The ninth and last field, called Gross, is the grossing revenue. However, only (some of) the movies have this value.
Therefore, this can get dropped or alternatively, depending on the objective of the study, these could
be the only ones kept if knowing the grossing revenue is necessary.



'''

In [13]:
from google.colab import files
upload = files.upload()

Saving movies.csv to movies.csv

In [137]:
# question mentionned code wasn't needed but trying a few of the data cleaning processes here

df = pd.read_csv("/content/movies.csv")


df = df.replace(r'\n',' ', regex=True)
df = df.replace(r"\(","", regex=True) #getting rid of parentheses and new tabs, should make it into one regex
df = df.replace(r"\)","", regex=True)
df['YEAR'].replace(r"I",'', inplace=True, regex = True)
df.drop(index=df[df['ONE-LINE'].str.contains('Add a Plot')].index.copy(), inplace=True) #deleting all rows with no description
df = df[df['RATING'].notna()].copy() #only keeping items with a rating
df = df[df['Gross'].notna()].copy() #only keeping items with a grossing revenue (not necessary)
df['VOTES'] = df['VOTES'].apply(lambda x: int(x.split()[0].replace(',', ''))) #getting rid of commas to be able to transform to integers
df['VOTES'] = df['VOTES'].astype(int) #transforming strings in the VOTES column to integers
df = df[df.VOTES > 100] #only keeping items with more than 100 votes
df.rename(columns = {"MOVIES": "MOVIE/SHOW", "ONE-LINE": "DESCRIPTION", "STARS": "STARRING"}, inplace = True) #changing some column names to be more descriptive
df = df.replace(".*(Stars:)", " ", regex=True) #everything before the names of the stars gets deleted


#df.to_csv('movies_cleaned.csv') # saving dataframe as a new csv file for the cleaned data
df.head()

,MOVIE/SHOW,YEAR,GENRE,RATING,DESCRIPTION,STARRING,VOTES,RunTime,Gross
77,The Hitman's Bodyguard,2017,"Action, Comedy, Crime",6.9,"The world's top bodyguard gets a new client, ...","Ryan Reynolds, Samuel L. Jackson, Gary Old...",205979,118.0,$75.47M
85,Jurassic Park,1993,"Action, Adventure, Sci-Fi",8.1,A pragmatic paleontologist visiting an almost...,"Sam Neill, Laura Dern, Jeff Goldblum, Ric...",897444,127.0,$402.45M
95,Don't Breathe,2016,"Crime, Horror, Thriller",7.1,"Hoping to walk away with a massive fortune, a...","Stephen Lang, Jane Levy, Dylan Minnette, ...",237601,88.0,$89.22M
111,The Lord of the Rings: The Fellowship of the Ring,2001,"Action, Adventure, Drama",8.8,A meek Hobbit from the Shire and eight compan...,"Elijah Wood, Ian McKellen, Orlando Bloom, ...",1713028,178.0,$315.54M
125,Escape Room,2019,"Action, Adventure, Horror",6.4,Six strangers find themselves in a maze of de...,"Taylor Russell, Logan Miller, Jay Ellis, ...",99351,99.0,$57.01M